version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  server:
    build: ./server
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/postgres}
      FLASK_DEBUG: "1"
    depends_on: [db]
    ports: ["8000:8000"]
    volumes:
      - server_data:/app/data

volumes:
  pgdata:
  server_data: